spring.application.name=SDP_07_ElectionMonitoringSystem
server.port=2005

#connection properties

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sdp07
spring.datasource.username=root
spring.datasource.password=root

#hibernate properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect